// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------
/************************************************************/
/**
 * 
 */
import java.text.DecimalFormat; // Import a decimal format
/**
 * 
 */
public class Employee {
	/**
	 * 
	 */
	protected byte scriptsDone;
	protected float monthlySalary, tax, prsi, takeHomePay, additionalPayment;
	protected String ppsNumber;
	protected boolean validPPS, validScriptsDone;
	DecimalFormat money = new DecimalFormat("\u20AC0.00"); //Decimal format for Euro character that showing 2 number after dot
	
	public void readEmpDetails() {		
			do {
				try {
					do {
						System.out.print("\nPlease enter your PPS number: "); // Asking user to enter a PPS number
						ppsNumber = FullAndPartTimeMain.sc.next();

						boolean valid0 = Character.isDigit(ppsNumber.charAt(0));
						boolean valid1 = Character.isDigit(ppsNumber.charAt(1));
						boolean valid2 = Character.isDigit(ppsNumber.charAt(2));
						boolean valid3 = Character.isDigit(ppsNumber.charAt(3));
						boolean valid4 = Character.isDigit(ppsNumber.charAt(4));
						boolean valid5 = Character.isDigit(ppsNumber.charAt(5));
						boolean valid6 = Character.isDigit(ppsNumber.charAt(6));
						boolean valid7 = Character.isDigit(ppsNumber.charAt(7));

						if (ppsNumber.length() > 8 || ppsNumber.length() < 0 || valid7 == true || valid0 == false
								|| valid1 == false || valid2 == false || valid3 == false || valid4 == false
								|| valid5 == false || valid6 == false) {
							System.err.print("\nYour PPS number must have 7 digits and 1 letter."); // Output error
							validPPS = false;
						} else {
							validPPS = true;
						}
					} while (!validPPS); // Working until user enter a valid number
				} catch (java.lang.StringIndexOutOfBoundsException e) {
					System.err.print("Sorry, you entered the wrong PPS number."); // Error if entered PPS less than 7 numbers.
				} 
			} while (!validPPS);
	}

	
	public void calculatePRSI() {
		prsi = monthlySalary*4/100;
	}
	/**
	 * 
	 */
	public void calculateTakeHomePay() {
		takeHomePay = monthlySalary-prsi-tax;
	}
	/**
	 * 
	 */
	public void outputTakeHomePay() {
		System.out.printf("\n%-20s %s", "PPS Number:", ppsNumber);
		System.out.printf("\n%-20s %s", "Gross pay:", money.format(monthlySalary));
		System.out.printf("\n%-20s %s", "TAX:", money.format(tax));
		System.out.printf("\n%-20s %s", "PRSI:", money.format(prsi));
		System.out.printf("\n%-20s %s", "Take home pay:", money.format(takeHomePay));
	}
}
