// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class FullTime extends Employee {
	/**
	 * 
	 */
	private byte daysLeave, point;
	/**
	 * 
	 */
	private float basicSalary = 3343.58f;
	/**
	 * 
	 */
	private boolean validDaysLeave, validPoint;
	/**
	 * 
	 */
	public void processDaysLeave() {
		 do {
            try {
                do {
                    System.out.print("\nEnter how many days you were absent:");
                    daysLeave = FullAndPartTimeMain.sc.nextByte();
                    if (daysLeave < 0 || daysLeave > 31) {
                        System.err.println("Sorry, something wrong, maximum number of absent days 31."); 
                    }
                } while (daysLeave < 0 || daysLeave > 31);
                 validDaysLeave = true; // Stopping asking.
            }
            catch(java.util.InputMismatchException e){
                System.err.println("Please use numbers."); // In case if user entered a letters
                FullAndPartTimeMain.sc.next(); //Call scanner again
            }
        } while (!validDaysLeave);
	}
	
	
	public void getScriptsDone() {
		do {
            try {
                do {
                    System.out.print("\nEnter how many scripts you have done:");
                    scriptsDone = FullAndPartTimeMain.sc.nextByte();
                    if (scriptsDone < 0) {
                        System.err.println("Sorry, something wrong, try again."); 
                    }
                } while (scriptsDone < 0);
                 validScriptsDone = true; // Stopping asking.
            }
            catch(java.util.InputMismatchException e){
                System.err.println("Please use numbers."); // In case if user entered a letters
                FullAndPartTimeMain.sc.next(); //Call scanner again
            }
        } while (!validScriptsDone);
	}
	public void getPoint() {
		do {
            try {
                do {
                    System.out.print("\nEnter your point on the common basic scale:");
                    point = FullAndPartTimeMain.sc.nextByte();
                    if (point < 1 || point > 4) {
                        System.err.println("Sorry, you should enter number from 1 to 4."); 
                    }
                    switch (point) {
                    case 1: {
                    	additionalPayment = 426.67f;
                    	break;
                    	}
                    case 2: {
                    	additionalPayment = 565.75f;
                    	break;
                    	}
                    case 3: {
                    	additionalPayment = 666.58f;
                    	break;
                    	}
                    case 4: {
                    	additionalPayment = 750.00f;
                    	break;
                    	}                 
                    }                   
                } while (point < 1 || point > 4);
                 validPoint = true; // Stopping asking.
            }
            catch(java.util.InputMismatchException e){
                System.err.println("Please use numbers."); // In case if user entered a letters
                FullAndPartTimeMain.sc.next(); //Call scanner again
            }
        } while (!validPoint);
	}
	
	public void calculateMontlySalary() {
		additionalPayment += scriptsDone*10.18; // adding payment for done scripts
		monthlySalary = basicSalary + additionalPayment - (daysLeave*62.68f);
	}
	
	
	
	public void calculateTax() {
		if (monthlySalary*12 < 40000) {
			tax = monthlySalary*22/100;
		} else {
			tax = (((40000f/12)*22/100)+((monthlySalary-(40000f/12))*42/100));
		}
	}

	
}
