// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

/************************************************************/
/**
 * 
 */
public class Principal extends Employee {
	/**
	 * 
	 */
	private int nubmerOfTeachers;
	private float basicSalary= 5000;
	private boolean validNumberOfTeachers;

	public void getNumberOfTeachers() {
		do {
            try {
                do {
                    System.out.print("\nEnter how many teachers in the school:");
                    nubmerOfTeachers = FullAndPartTimeMain.sc.nextInt();
                    if (nubmerOfTeachers < 0) {
                        System.err.println("Sorry, something wrong, try again."); 
                    }
                } while (nubmerOfTeachers < 0);
                 validNumberOfTeachers = true; // Stopping asking.
            }
            catch(java.util.InputMismatchException e){
                System.err.println("Please use numbers."); // In case if user entered a letters
                FullAndPartTimeMain.sc.next(); //Call scanner again
            }
        } while (!validNumberOfTeachers);
		
		if (nubmerOfTeachers < 9) {
			additionalPayment = 775.83f;
		}
		else if (nubmerOfTeachers < 99) {
			additionalPayment = 869.33f;
		}
		else if (nubmerOfTeachers < 199) {
			additionalPayment = 1019.83f;
		} else {
			additionalPayment = 1196.67f;
		}
	}
	public void calculateMontlySalary() {
		monthlySalary = basicSalary + additionalPayment;
	}
	/**
	 * 
	 */
	public void calculateTax() {
		if (monthlySalary*12 < 40000) {
			tax = monthlySalary*22/100;
		} else {
			tax = (((40000f/12)*22/100)+((monthlySalary-(40000f/12))*42/100));
		}
	}
	
	
}
